tjbash/urls.py
from django.conf.urls import url
from django.contrib import admin
from quotes import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index_view, name="index"),
    url(r'^quotes/all/$', views.view_all_quotes, name="all_quotes"),
    url(r'^quotes/unapproved/$', views.view_unapproved_quotes, name="unapproved_quotes"),
    url(r'^quotes/top/$', views.view_top_quotes, name="top_quotes"),
    url(r'^quotes/bottom/$', views.view_bottom_quotes, name="bottom_quotes"),
    url(r'^quotes/new/$', views.create_new_quote, name="new_quote"),
    url(r'^tags/$', views.view_all_tags, name="view_all_tags"),
    url(r'^quotes/tag/$', views.view_quotes_by_tag, name="quotes_by_tag"),
    url(r'^quotes/approve/(?P<qid>\d+)/$', views.approve_quote, name="approve_quote"),
    url(r'^quotes/delete/$', views.delete_quote, name="delete_quote"),
    url(r'^quotes/edit/(?P<qid>\d+)/', views.edit_quote, name="edit_quote"),
    url(r'^quotes/upvote/', views.upvote_quote, name="upvote_quote"),
    url(r'^quotes/downvote/', views.downvote_quote, name="downvote_quote"),
    url(r'^quotes/permalink/(?P<qid>\d+)/$', views.view_quote, name="view_quote"),
    url(r'^announcements/new/$', views.add_announcement, name="new_announcement"),
    url(r'^announcements/edit/(?P<aid>\d+)/', views.edit_announcement, name="edit_announcement"),
]

quotes/models.py
from django.db import models

# Create your models here.


class Announcement(models.Model):
    content = models.TextField(max_length=750)
    creation_time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content


class Tag(models.Model):
    name = models.CharField(max_length=250)

    def __str__(self):
        return self.name


class Quote(models.Model):
    content = models.TextField(max_length=750)
    tags = models.ManyToManyField(Tag, related_name="quotes")
    approved = models.BooleanField(default=False)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.content

quotes/forms.py
from django import forms
from .models import Announcement, Quote


class AnnouncementForm(forms.ModelForm):
    class Meta:
        model = Announcement
        fields = ["content"]

    def __init__(self, *args, **kwargs):
        super(AnnouncementForm, self).__init__(*args, **kwargs)
        self.fields['content'].widget = forms.widgets.Textarea(attrs={'class': 'materialize-textarea'})


class QuoteForm(forms.ModelForm):
    tags = forms.CharField(required=False)

    class Meta:
        model = Quote
        fields = ["content"]

    def __init__(self, *args, **kwargs):
        super(QuoteForm, self).__init__(*args, **kwargs)
        self.fields['content'].widget = forms.widgets.Textarea(attrs={'class': 'materialize-textarea'})

quotes/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.conf import settings
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.http.response import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Count


from .models import Announcement, Quote, Tag
from .forms import AnnouncementForm, QuoteForm

import bleach
import json
import re
import requests
from requests_oauthlib import OAuth1


def notify_twitter(status):
    url = 'https://api.twitter.com/1.1/statuses/update.json'

    auth = OAuth1(settings.TWITTER_CONSUMER_KEY, settings.TWITTER_CONSUMER_SECRET, settings.TWITTER_ACCESS_TOKEN, settings.TWITTER_ACCESS_SECRET)

    data = {"status": status}

    req = requests.post(url, data=data, auth=auth)

    return req.text

def post_to_twitter(request, quote):
    url = request.build_absolute_uri(reverse('view_quote', args=[quote.id]))
    content = quote.content
    content = content.replace("<br>", "\n")
    content = re.sub('<[^>]*>', '', content)
    content = content.replace("&nbsp;", " ")
    content_len = 130 - len(url)
    text = "{}{} - {}".format(content[:content_len],"..." if len(content) > content_len else "", url)
    resp = notify_twitter(text)
    respobj = json.loads(resp)

    if respobj and "id" in respobj:
        messages.success(request, "Posted tweet: {}".format(text))
        messages.success(request, "https://twitter.com/tjbash_qdb/status/{}".format(respobj["id"]))
    else:
        messages.error(request, resp)

# Create your views here.


def index_view(request):
    context = {
        "announcements": Announcement.objects.all().order_by('-creation_time')[:5],
        "num_quotes": Quote.objects.filter(approved=True).count(),
        "approval_quotes": Quote.objects.filter(approved=False).count(),
    }
    return render(request, "index.html", context)


def view_quote(request, qid):
    quote = get_object_or_404(Quote, pk=qid)
    return render(request, "quotes.html", {"quotes": [quote]})


def view_all_tags(request):
    tags = Tag.objects.annotate(quote_count=Count('quotes')).filter(quote_count__gte=1).filter(quotes__approved=True)
    tags_list = [{"text": tag.name, "weight": tag.quotes.count(), "link": "{}?tag={}".format(reverse("quotes_by_tag"), tag.name)} for tag in tags]
    return render(request, "tags.html", {"tags": tags_list})


def view_all_quotes(request):
    quotes_list = Quote.objects.filter(approved=True).order_by('-id')
    paginator = Paginator(quotes_list, 10)
    page = request.GET.get('page')
    try:
        quotes = paginator.page(page)
    except PageNotAnInteger:
        quotes = paginator.page(1)
    except EmptyPage:
        quotes = paginator.page(paginator.num_pages)
    context = {
        "quotes": quotes
    }
    return render(request, "quotes.html", context)


def view_top_quotes(request):
    quotes_list = Quote.objects.filter(approved=True).order_by('-votes')
    paginator = Paginator(quotes_list, 10)
    page = request.GET.get('page')
    try:
        quotes = paginator.page(page)
    except PageNotAnInteger:
        quotes = paginator.page(1)
    except EmptyPage:
        quotes = paginator.page(paginator.num_pages)
    context = {
        "quotes": quotes
    }
    return render(request, "quotes.html", context)


def view_bottom_quotes(request):
    quotes_list = Quote.objects.filter(approved=True).order_by('votes')
    paginator = Paginator(quotes_list, 10)
    page = request.GET.get('page')
    try:
        quotes = paginator.page(page)
    except PageNotAnInteger:
        quotes = paginator.page(1)
    except EmptyPage:
        quotes = paginator.page(paginator.num_pages)
    context = {
        "quotes": quotes
    }
    return render(request, "quotes.html", context)


def view_quotes_by_tag(request):
    quotes_list = Quote.objects.filter(approved=True, tags__name=request.GET.get("tag", "")).order_by('-votes')
    paginator = Paginator(quotes_list, 10)
    page = request.GET.get('page')
    try:
        quotes = paginator.page(page)
    except PageNotAnInteger:
        quotes = paginator.page(1)
    except EmptyPage:
        quotes = paginator.page(paginator.num_pages)
    context = {
        "quotes": quotes
    }
    return render(request, "quotes.html", context)


def create_new_quote(request):
    if request.method == "POST":
        form = QuoteForm(request.POST)
        if form.is_valid():
            tag_names = form.cleaned_data["tags"].split(",")
            obj = form.save(commit=True)
            obj.content = bleach.clean(obj.content.replace("\r\n", "<br>"), tags=[u"br"])
            obj.save()
            for tag_name in tag_names:
                if len(tag_name.lower().strip()) > 0:
                    tag, created = Tag.objects.get_or_create(name=tag_name.lower().strip())
                    obj.tags.add(tag)
            messages.success(request, "Quote submitted for approval!")
            return redirect("all_quotes")
        else:
            messages.error(request, "Error adding quote :(")
    else:
        form = QuoteForm()
    tag_list = Tag.objects.filter(quotes__approved=True)
    return render(request, "form.html", {"form": form, "action": reverse("new_quote"), "tags": tag_list})


@login_required
def edit_quote(request, qid):
    quote = get_object_or_404(Quote, pk=qid)
    if request.method == "POST":
        form = QuoteForm(request.POST, instance=quote)
        if form.is_valid():
            tag_names = form.cleaned_data["tags"].split(",")
            obj = form.save()
            obj.content = bleach.clean(obj.content.replace("\r\n", "<br>"), tags=[u"br"])
            obj.save()
            for tag_name in tag_names:
                tag, created = Tag.objects.get_or_create(name=tag_name)
                obj.tags.add(tag)
            return redirect("all_quotes")
        else:
            messages.error(request, "Error adding quote :(")
    else:
        form = QuoteForm(instance=quote)
    return render(request, "form.html", {"form": form, "action": reverse("edit_quote", kwargs={"qid": qid})})


@login_required
def add_announcement(request):
    if request.method == "POST":
        form = AnnouncementForm(request.POST)
        if form.is_valid():
            obj = form.save()
            obj.content = bleach.clean(obj.content.replace("\r\n", "<br>"), tags=[u"br"])
            obj.save()
            return redirect("index")
        else:
            messages.error(request, "Error adding announcement :(")
    else:
        form = AnnouncementForm()
    return render(request, "form.html", {"form": form, "action": reverse("new_announcement")})


@login_required
def edit_announcement(request, aid):
    ann = get_object_or_404(Announcement, pk=aid)
    if request.method == "POST":
        form = AnnouncementForm(request.POST, instance=ann)
        if form.is_valid():
            obj = form.save()
            obj.content = bleach.clean(obj.content.replace("\r\n", "<br>"), tags=[u"br"])
            obj.save()
            return redirect("index")
        else:
            messages.error(request, "Error adding announcement :(")
    else:
        form = AnnouncementForm(instance=ann)
    return render(request, "form.html", {"form": form, "action": reverse("edit_announcement", kwargs={"aid": aid})})


def upvote_quote(request):
    if request.method == "POST":
        qid = request.POST.get("qid", -1)
        quote = get_object_or_404(Quote, pk=qid)
        if qid in request.session.get("upvoted", []):
            return HttpResponse("already upvoted", content_type="text/plain")
        already_upvoted = request.session.get("upvoted", [])
        already_upvoted.append(qid)
        request.session['upvoted'] = already_upvoted
        quote.votes += 1
        quote.save()
    return redirect("all_quotes")


def downvote_quote(request):
    if request.method == "POST":
        qid = request.POST.get("qid", -1)
        quote = get_object_or_404(Quote, pk=qid)
        if qid in request.session.get("downvoted", []):
            return HttpResponse("already downvoted", content_type="text/plain")
        already_downvoted = request.session.get("downvoted", [])
        already_downvoted.append(qid)
        request.session['downvoted'] = already_downvoted
        quote.votes -= 1
        quote.save()
    return redirect("all_quotes")


@login_required
def approve_quote(request, qid):
    quote = get_object_or_404(Quote, pk=qid)
    quote.approved = True
    quote.save()
    post_to_twitter(request, quote)
    return redirect("unapproved_quotes")


@login_required
def delete_quote(request):
    if request.method == "POST":
        quote = get_object_or_404(Quote, pk=request.POST.get("qid", -1))
        quote.delete()
    return redirect("unapproved_quotes")


@login_required
def view_unapproved_quotes(request):
    quotes_list = Quote.objects.filter(approved=False)
    paginator = Paginator(quotes_list, 10)
    page = request.GET.get('page')
    try:
        quotes = paginator.page(page)
    except PageNotAnInteger:
        quotes = paginator.page(1)
    except EmptyPage:
        quotes = paginator.page(paginator.num_pages)
    context = {
        "quotes": quotes
    }
    return render(request, "quotes.html", context)

templates/announcement.html
<div class="card-panel">
    <span class="black-text">{{ announcement.content|safe }}</span>
    <br />
    <span class="grey-text">{{ announcement.creation_time }}</span>
    <br />
    {% if request.user.is_authenticated and request.user.is_superuser %}
    <a href="{% url 'edit_announcement' announcement.id %}">Edit</a>
    {% endif %}
</div>

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>

        <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon" />
        <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon" />

        <title>TJ Bash 2.0</title>

        <!-- CSS  -->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/css/materialize.min.css" media="screen,projection">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.4/css/selectize.css" />
        <link href="{% static 'css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
        {% block css %}{% endblock %}
    </head>
    <body>
        <nav class="purple darken-2" role="navigation">
            <div class="nav-wrapper container"><a id="logo-container" href="{% url 'index' %}" class="brand-logo">TJ Bash 2.0</a>
                <ul class="right hide-on-med-and-down">
                    <li><a href="{% url 'new_quote' %}">New Quote</a></li>
                    <li><a href="{% url 'all_quotes' %}">Browse</a></li>
                    <li><a href="{% url 'top_quotes' %}">Top</a></li>
                    <li><a href="{% url 'bottom_quotes' %}">Bottom</a></li>
                    <li><a href="{% url 'view_all_tags' %}">Tags</a></li>
                    {% if request.user.is_authenticated and request.user.is_superuser %}
                    <li><a href="{% url 'unapproved_quotes' %}">Unapproved Quotes</a></li>
                    <li><a href="{% url 'new_announcement' %}">New Announcement</a></li>
                    {% endif %}
                </ul>

                <ul id="nav-mobile" class="side-nav">
                    <li><a href="{% url 'new_quote' %}">New Quote</a></li>
                    <li><a href="{% url 'all_quotes' %}">Browse</a></li>
                    <li><a href="{% url 'top_quotes' %}">Top</a></li>
                    <li><a href="{% url 'bottom_quotes' %}">Bottom</a></li>
                    <li><a href="{% url 'view_all_tags' %}">Tags</a></li>
                    {% if request.user.is_authenticated and request.user.is_superuser %}
                    <li><a href="{% url 'unapproved_quotes' %}">Unapproved Quotes</a></li>
                    <li><a href="{% url 'new_announcement' %}">New Announcement</a></li>
                    {% endif %}
                </ul>
                <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
            </div>
        </nav>

        <main>
        <div class="container">
            {% block content %}{% endblock %}
        </div>
        </main>

        <footer class="page-footer deep-purple darken-3">
            <div class="container">
                <div class="row">
                    <div class="col s12">
                        <h5 class="white-text">TJ Bash 2.0</h5>
                        <p class="grey-text text-lighten-4">tjbash.com does not have any affiliation with the Thomas Jefferson High School for Science and Technology. Quotes on tjbash.com do not necessarily reflect the views of the authors, administrators, or moderators of this site, nor do they reflect the views of the Thomas Jefferson High School for Science and Technology.

                        The name "tjbash.com" is not meant as a derogatory comment towards TJHSST or any entity - it does not refer to "bashing" and should not be taken as such. The name comes from tjbash.org, a similar online quote database.

                        Quotes on tjbash.com have no implicit or explicit claim of validity - all quotes are unverified.</p>


                    </div>
                </div>
            </div>
            <div class="footer-copyright">
                <div class="container">
                    &copy; 2017 <a class="white-text" href="mailto:comments@tjbash.com" rel="noopener noreferrer" target="_blank">Omkar Kulkarni</a>
                </div>
            </div>
        </footer>


        <!--  Scripts-->
        <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/js/materialize.min.js"></script>
        <script src="{% static 'js/selectize.min.js' %}"></script>
        <script src="{% static 'js/init.js' %}"></script>
        {% if messages|length > 0 %}
        <script type="text/javascript">
            $(document).ready(function() {
                {% for message in messages %}
                Materialize.toast("{{ message }}", 2000);
                {% endfor %}
            });
        </script>
        {% endif %}
        {% block scripts %}{% endblock %}

</body>
</html>

templates/form.html
{% extends "base.html" %}
{% block content %}
<div class="section">
    <form action="{{ action }}" method="POST">
        {% csrf_token %}
        {{ form }}
        <button class="btn waves-effect waves-light" type="submit" name="action">Submit
            <i class="material-icons right">send</i>
        </button>
    </form>
</div>
{% endblock %}
{% block scripts %}
<script type="text/javascript">
    $('#id_tags').selectize({
        options: [
            {% for tag in tags %}{
                'value': '{{ tag.name }}',
                'text': '{{tag.name}}'
            }{% if not forloop.last %}, {% endif %}{% endfor %}
        ],
        delimiter: ',',
        maxItems: null,
        persist: false,
        create: function(input) {
            return {
                value: input,
                text: input
            }
        }
    });
</script>
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block content %}
<div class="section">
    <div class="row">
        <div class="col l6 s12">
            <p> Welcome to tjbash.com! tjbash.com is a quote repository similar to the famous QDB at tjbash.org. We feature quotes by TJHSST students, alumni, and faculty. Obviously, this means our screening procedures are much more lax, giving you a better chance of seeing your own humorous personal experiences posted. Of course, this does not mean that tjbash.com quotes must be TJ related or that the tjbash.com site is limited to the TJ community - submitted quotes can be about any topic and other users familiar to the TJ cause or the TJ community are welcome to read and add quotes at tjbash.com.

            Depending on if you like or dislike a quote, there are links to upvote and downvote quotes. If you think a quote should not be in the database or you have any questions, comments, or concerns, send us an email at <a href="mailto:comments@tjbash.com" target="_blank" rel="noopener noreferrer">comments@tjbash.com</a>.

            Currently, the database contains a total of {{ num_quotes }} quote{{ num_quotes | pluralize }}. There {{ approval_quotes | pluralize:"is,are" }} {{ approval_quotes }} quote{{ approval_quotes | pluralize }} awaiting moderation.</p>
        </div>
        <div class="col l6 s12">
            {% for announcement in announcements %}
                {% include "announcement.html" with announcement=announcement %}
            {% empty %}
                <h5>There are no announcements at this time</h5>
            {% endfor %}
        </div>
</div>
{% endblock %}

templates/quote.html
<div class="card sticky-action">
    <div class="card-content black-text">
        <span class="card-title"><a href="{% url 'view_quote' quote.id %}" class="black-text"><u>Quote #{{ quote.id }}</u></a></span>
        <p>{{ quote.content|safe }}</p>
        {% if quote.tags.count > 0 %}
        <p class="grey-text">Tags:
            {% for tag in quote.tags.all %}
            <a href="/quotes/tag/?tag={{ tag }}">{{ tag }}</a>{% if not forloop.last %},{% endif %}
            {% endfor %}
        </p>
        {% endif %}
        <p class="grey-text">Votes: <span id="votes_{{ quote.id }}">{{ quote.votes }}</span> vote{{ quote.votes|pluralize }}</p>
    </div>
    <div class="card-action">
        <div class="row">
            {% if request.user.is_authenticated and request.user.is_superuser %}
                {% if not quote.approved %}
                    <div class="col s3 center-align">
                {% else %}
                    <div class="col s4 center-align">
                {% endif %}
            {% else %}
                <div class="col s6 center-align">
            {% endif %}
                    <a href="#!" class="waves-effect waves-green btn-flat upvote-link green-text" data-id="{{ quote.id }}"><i class="material-icons left">check</i> Upvote</a>
                </div>
            {% if request.user.is_authenticated and request.user.is_superuser %}
                {% if not quote.approved %}
                    <div class="col s3 center-align">
                {% else %}
                    <div class="col s4 center-align">
                {% endif %}
            {% else %}
                <div class="col s6 center-align">
            {% endif %}
                <a href="#!" class="waves-effect waves-red btn-flat downvote-link red-text" data-id="{{ quote.id }}"><i class="material-icons left">clear</i> Downvote</a>
            </div>
            {% if request.user.is_authenticated and request.user.is_superuser %}
                {% if not quote.approved %}
                <div class="col s3 center-align">
                    <a href="{% url 'approve_quote' quote.id %}" class="waves-effect waves-green btn-flat black-text">Approve</a>
                </div>
                <div class="col s3 center-align">
                    <a href="#!" class="waves-effect waves-red btn-flat black-text delete-link" data-id="{{ quote.id }}">Delete</a>
                </div>
                {% else %}
                <div class="col s4 center-align">
                    <a href="#!" class="waves-effect waves-red btn-flat black-text delete-link" data-id="{{ quote.id }}">Delete</a>
                </div>
                {% endif %}
            {% endif %}
        </div>
    </div>
</div>

templates/quotes.html
{% extends "base.html" %}
{% block content %}
<div class="section">
    {% if quotes.paginator %}
    <div class="row">
        <div class="col s12 center-align">
            <a href="{% if quotes.has_previous %}?page={{ quotes.previous_page_number }}{% else %}#!{% endif %}{% if request.GET.tag %}&tag={{ request.GET.tag }}{% endif %}" class="{% if quotes.has_previous %}black-text{% else %}grey-text{% endif %}"><u>Previous Page</u> &nbsp;</a>
            <span class="current">
                Page {{ quotes.number }} of {{ quotes.paginator.num_pages }}
            </span>

            <a href="{% if quotes.has_next %}?page={{ quotes.next_page_number }}{% else %}#!{% endif %}{% if request.GET.tag %}&tag={{ request.GET.tag }}{% endif %}" class="{% if quotes.has_next %}black-text{% else %}grey-text{% endif %}">&nbsp; <u>Next Page</u></a>
        </div>
    </div>
    {% endif %}
    {% for quote in quotes %}
    <div class="row" id="quote-{{ quote.id }}">
        <div class="col s12">
            {% include "quote.html" with quote=quote %}
        </div>
    </div>
    {% empty %}
    <h5>There are no quotes at this time :(</h5>
    {% endfor %}
    {% if quotes.paginator %}
    <div class="row">
        <div class="col s12 center-align">
            <a href="{% if quotes.has_previous %}?page={{ quotes.previous_page_number }}{% else %}#!{% endif %}{% if request.GET.tag %}&tag={{ request.GET.tag }}{% endif %}" class="{% if quotes.has_previous %}black-text{% else %}grey-text{% endif %}"><u>Previous Page</u> &nbsp;</a>
            <span class="current">
                Page {{ quotes.number }} of {{ quotes.paginator.num_pages }}
            </span>

            <a href="{% if quotes.has_next %}?page={{ quotes.next_page_number }}{% else %}#!{% endif %}{% if request.GET.tag %}&tag={{ request.GET.tag }}{% endif %}" class="{% if quotes.has_next %}black-text{% else %}grey-text{% endif %}">&nbsp; <u>Next Page</u></a>
        </div>
    </div>
    {% endif %}
</div>
{% csrf_token %}
{% endblock %}
{% block scripts %}
<script type="text/javascript">
    $(document).ready(function() {
        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
        var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();
        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });
        $(".upvote-link").on("click", function(e) {
            e.preventDefault();
            var id = parseInt($(this).data("id"));
            $.post("{% url 'upvote_quote' %}", { qid: id }).done(function(response) {
                if(response === "already upvoted") {
                    Materialize.toast("You have already upvoted this quote!", 2000);
                    return;
                }
                $("#votes_"+id).text(parseInt($("#votes_"+id).text())+1);
            }).fail(function() {
                Materialize.toast("Error upvoting the quote :(", 2000);
            });
        });
        $(".downvote-link").on("click", function(e) {
            e.preventDefault();
            var id = parseInt($(this).data("id"));
            $.post("{% url 'downvote_quote' %}", { qid: id }).done(function(response) {
                if(response === "already downvoted") {
                    Materialize.toast("You have already downvoted this quote!", 2000);
                    return;
                }
                $("#votes_"+id).text(parseInt($("#votes_"+id).text())-1);
            }).fail(function() {
                Materialize.toast("Error downvoting the quote :(", 2000);
            });
        });
        $(".delete-link").on("click", function(e) {
            e.preventDefault();
            var id = parseInt($(this).data("id"));
            $.post("{% url 'delete_quote' %}", {"qid":id}).done(function(response) {
                $("#quote-"+id).remove();
                Materialize.toast("Deleted quote!", 2000);
            }).fail(function() {
                Materialize.toast("Error deleting quote :(");
            });
        });
    });
</script>
{% endblock %}

templates/tags.html
{% extends "base.html" %}
{% block css %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqcloud/1.0.4/jqcloud.css" />
<style type="text/css">
	#tags_cloud {
		width: 100%;
		height: 500px;
	}
</style>
{% endblock %}
{% block content %}
<div class="section">
    <div class="row">
        <div class="col s12">
            <div id="tags_cloud">
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block scripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqcloud/1.0.4/jqcloud-1.0.4.min.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
        words = {{ tags|safe }};
        $("#tags_cloud").jQCloud(words);
    });
</script>
{% endblock %}